### ISSUE TITLE
Crew view doesn't work if worked with multiple movies

### ISSUE THREAD

**Issue by jerinphilip** [darkcoderrises/Movie-Recommender#18]
Please print the crews sorted by the number of movies they were part of.  Also, find the stack trace of the error below.

```
[01/Apr/2018 15:45:46] "GET /movie/17447/ HTTP/1.1" 200 7582
Internal Server Error: /crew/156/
Traceback (most recent call last):
  File "/home/jerin/college/s18/se/Movie-Recommender/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/jerin/college/s18/se/Movie-Recommender/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jerin/college/s18/se/Movie-Recommender/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jerin/college/s18/se/Movie-Recommender/movie_recommender/booking_system/views.py", line 121, in crew
    _movies = Movie.objects.get(crew=_crew_type.id)
  File "/home/jerin/college/s18/se/Movie-Recommender/env/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/jerin/college/s18/se/Movie-Recommender/env/lib/python3.6/site-packages/django/db/models/query.py", line 407, in get
    (self.model._meta.object_name, num)
booking_system.models.MultipleObjectsReturned: get() returned more than one Movie -- it returned 2!
[01/Apr/2018 15:45:47] "GET /crew/156/ HTTP/1.1" 500 76924

```

**Comment by AGangrade** [comment]
Issue resolved. Check once.
