### ISSUE TITLE
Search Feature on  Movie, Cast, Theatres.

### ISSUE THREAD

**Issue by jerinphilip** [darkcoderrises/Movie-Recommender#6]
Hopefully reusable, on an object.

**Comment by jerinphilip** [comment]
```
Internal Server Error: /search/
Traceback (most recent call last):
  File "/home/jerin/college/s18/soft-engg/Movie-Recommender/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/jerin/college/s18/soft-engg/Movie-Recommender/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jerin/college/s18/soft-engg/Movie-Recommender/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jerin/college/s18/soft-engg/Movie-Recommender/movie_recommender/booking_system/views.py", line 60, in search
    movie_filter = UserFilter(request.GET, queryset=movie_list)
NameError: name 'UserFilter' is not defined
```

@mandarGG , please find a fix.

**Comment by mandarGG** [comment]
added relevant files and imports to fix

**Comment by jerinphilip** [comment]
@mandarGG, can you implement multiple search and finish this one up, quickly?

**Comment by jerinphilip** [comment]
@mandarGG : Post question on stackoverflow, and haystack. We'd hopefully get response in a while.

**Comment by jerinphilip** [comment]
Issue was attempted indexing of a ForeignKey. Soon as Foreign Keys were commented out, the build index time errors went away. 

Search is returning empty now though.
